### ISSUE TITLE
Related lookup button overlaps m2m raw id inputs

### ISSUE THREAD

**Issue by BertrandBordage** [sehmaschine/django-grappelli#333]
Because this button overlaps the input, we can't see the end of that input:

Current rendering:
![](http://i.imgur.com/3hR93yV.png)
Expected rendering:
![](http://i.imgur.com/75aRGDe.png)

I got the expected output using this additional CSS:

``` css
input.vManyToManyRawIdAdminField {
  border-right: 0;
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
  padding: 2px 6px 2px 5px;
}

input.vManyToManyRawIdAdminField+a.related-lookup {
  margin: 0 0 0 -1px;
}
```

The -1px margin is done to hide the input outline.  To compensate, I increased the input padding-right.

M2m raw id inputs may not be the only ones to have this issue.
