### ISSUE TITLE
Overwriting css classes

### ISSUE THREAD

**Issue by dahfool** [sehmaschine/django-grappelli#797]
The way the component are styled, it's very difficult to overwrite the css. Eg
```css
header#grp-header #grp-navigation h1#grp-admin-title {
    font-size: 24px;
    letter-spacing: -0.2px;
}  
```
and in some cases the use of !important.
```css
.grp-object-tools li a:hover {
    opacity: 1 !important;
    border: 1px solid #2987a6 !important;
```
