### ISSUE TITLE
The changelist's dropdown filters are hidden by the footer

### ISSUE THREAD

**Issue by michelts** [sehmaschine/django-grappelli#83]
Hi Patrick!

In the changelist, when it is defined more filters than the screen can show, the dropdown box stay behind the footer row (with the actions) and we can't use the now invisible filters.

It seems to be very simple to fix it. I changed the file components.css. The footer has a z-index of 1000. The .module.filter has a z-index of 990. I put it over with a z-index of 1001:

``` css
.module.search,
.module.filter {
    position: relative;
    float: right;
    z-index: 1001;  /* it was 990 */
    padding: 8px 10px;
}
```

I tried another approach: just giving some padding over the dropdown so the overlaid area would be transparent/useless but I have no success. The padding would go on the .pulldown-container class but it has a shadow that prevent me from giving him a padding.

Do you want a pull request for it?
